name: kbo_predictor
description: Next Game Predictor App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^5.1.1
  shared_preferences: ^2.0.15
  timezone: ^0.9.4
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  table_calendar: ^3.0.9

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/PitchUP_Logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/PitchUP_Logo.png"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android : true
  ios : true


flutter_localizations:
  sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/kbo_games.csv
    - assets/data/kbo_hitter_players.csv
    - assets/data/kbo_pitcher_players.csv
    - assets/data/kbo_predictions.csv
    - assets/image/KIA.png
    - assets/image/KT.png
    - assets/image/LG.png
    - assets/image/NC.png
    - assets/image/SSG.png
    - assets/image/롯데.png
    - assets/image/삼성.png
    - assets/image/키움.png
    - assets/image/한화.png
    - assets/image/두산.png
    - assets/logo.png
    - assets/PitchUP_Logo.png
    - assets/data/kbo_win_lose.csv
